yesOrNoInput = 'Voulez-vous changer de repertoire pour le clonage des dépôts github yes/no ?\n'
WrongYesOrNoInput = 'Repondez par yes ou no\n'
repositoryPathInput = 'Veuillez saisir votre repertoire de clonage\n'
WrongPathDirectory = 'Le chemin spécifié est introuvable veuillez fournir un autre chemin\n'
FamixImporterPath = 'Veuillez spécifier le repertoire de base de votre importateur FamixTypeScriptImporter\n'